export const CityActionTypes = {
	ADD_CITY_WITH_DATA: "ADD_CITY_WITH_DATA",
	DELETE_CITY: "DELETE_CITY",
	FETCH_CITY_START: "FETCH_CITY_START",
	FETCH_CITY_SUCCESS: "FETCH_CITY_SUCCESS",
	FETCH_CITY_FAILURE: "FETCH_CITY_FAILURE",
};
