export const WeatherActionTypes = {
	FETCH_DAILY_READING_START: "FETCH_DAILY_READING_START",
	FETCH_DAILY_READING_FOR_ADD_START: "FETCH_DAILY_READING_FOR_ADD_START",
	FETCH_DAILY_READING_FOR_UPDATE_START:
		"FETCH_DAILY_READING_FOR_UPDATE_START",
	FETCH_DAILY_READING_FOR_ADD_SUCCESS: "FETCH_DAILY_READING_FOR_ADD_SUCCESS",
	FETCH_DAILY_READING_FOR_UPDATE_SUCCESS:
		"FETCH_DAILY_READING_FOR_UPDATE_SUCCESS",
	FETCH_DAILY_READING_FAILURE: "FETCH_DAILY_READING_FAILURE",
	SET_TIME_REFRESHED: "SET_TIME_REFRESHED",
};
