export const WeatherActionTypes = {
	FETCH_DAILY_READING_START: 'FETCH_DAILY_READING_START',
	FETCH_DAILY_READING_SUCCESS: 'FETCH_DAILY_READING_SUCCESS',
	FETCH_DAILY_READING_FAILURE: 'FETCH_DAILY_READING_FAILURE',
};

